
# Python Crash Course Exercises 



## Exercises 1

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

** What is 7 to the power of 4?**

In [1]:
7 ** 4

2401

** Split this string:**

    s = "Hi there Sam!"
    
**into a list. **

In [3]:
s = "Hi there Sam!"

In [4]:
s.split()

['Hi', 'there', 'Sam!']

** Given the variables:**

    planet = "Earth"
    diameter = 12742

** Use .format() to print the following string: **

    The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [6]:
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of Earth is 12742 kilometers.


** Given this nested list, use indexing to grab the word "hello" **

In [8]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [9]:
lst[3][1][2][0]

'hello'

** Given this nested dictionary grab the word "hello". Be prepared, this will be annoying/tricky **

In [11]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
d['k1'][3]['tricky'][3]['target'][3]


'hello'

** What is the main difference between a tuple and a list? **

In [ ]:
# Tuple is immutable and declared in round Bracket
# List is mutable and declard in Square Bracket

** Create a function that grabs the email website domain from a string in the form: **

    user@domain.com
    
**So for example, passing "user@domain.com" would return: domain.com**

In [13]:
def domainGet(x):
    return x.split('@')[-1]

In [14]:
domainGet('user@domain.com')

'domain.com'

### Exercises - 2 (Dictionary, Functions, Lambda, Map)

1. Find the words with the maximum count in `romeo.txt`

In [5]:
#@ First read the dataset
romeo_text =  open("C:/Users/Apsu/Desktop/Simplilearn_course1_folder/Day-1-materials/Datasets/romeo.txt")
contents = romeo_text.read()
print(contents)

But soft what light through yonder window breaks. It is the east and Juliet is the sun. 
Arise fair sun and kill the envious moon. Who is already sick and pale with grief



In [7]:
romeo_text

<_io.TextIOWrapper name='C:/Users/Apsu/Desktop/Simplilearn_course1_folder/Day-1-materials/Datasets/romeo.txt' mode='r' encoding='cp1252'>

In [13]:
 #@ count the words
   ...: # create count dictionary
   ...: counts = dict()
   ...: romeo_text =  open("C:/Users/Apsu/Desktop/Simplilearn_course1_folder/Day-1-materials/Datasets/romeo.txt")
   ...: for line in romeo_text:
   ...:     words = line.split()
   ...:     for word in words:
   ...:         counts[word] = counts.get(word, 0) + 1
counts

{'But': 1,
 'soft': 1,
 'what': 1,
 'light': 1,
 'through': 1,
 'yonder': 1,
 'window': 1,
 'breaks.': 1,
 'It': 1,
 'is': 3,
 'the': 3,
 'east': 1,
 'and': 3,
 'Juliet': 1,
 'sun.': 1,
 'Arise': 1,
 'fair': 1,
 'sun': 1,
 'kill': 1,
 'envious': 1,
 'moon.': 1,
 'Who': 1,
 'already': 1,
 'sick': 1,
 'pale': 1,
 'with': 1,
 'grief': 1}

In [20]:
counts.items()

dict_items([('But', 1), ('soft', 1), ('what', 1), ('light', 1), ('through', 1), ('yonder', 1), ('window', 1), ('breaks.', 1), ('It', 1), ('is', 3), ('the', 3), ('east', 1), ('and', 3), ('Juliet', 1), ('sun.', 1), ('Arise', 1), ('fair', 1), ('sun', 1), ('kill', 1), ('envious', 1), ('moon.', 1), ('Who', 1), ('already', 1), ('sick', 1), ('pale', 1), ('with', 1), ('grief', 1)])

In [17]:
 #find the words with maximum count  
   ...: bigword = []
   ...: 
   ...: for word,count in counts.items():   
   ...:     if count==max(counts.values()): 
   ...:         bigword.append((word,count))
   ...: 
   ...: print(bigword)

[('is', 3), ('the', 3), ('and', 3)]


In [19]:
 #find the words with maximum count  
   ...: bigword = {}
   ...: 
   ...: for word,count in counts.items():   
   ...:     if count==max(counts.values()): 
   ...:         bigword[word] = count
   ...: 
   ...: print(bigword)

{'is': 3, 'the': 3, 'and': 3}


In [27]:
 sorted(counts.values(), reverse = True)

[3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

2. Arrange all the words in decreasing order of word counts

In [36]:
 # words in decreasing order         
   ...: temp = []
   ...: temp1 = []
   ...: 
   ...: for w,k in counts.items():
   ...:     temp.append((k,w))
   ...:     temp1.append((w,k))
temp = sorted(temp, reverse = True)
temp1 = sorted(temp1, reverse = True)
print(temp)
print("-------------")
print(temp1)

[(3, 'the'), (3, 'is'), (3, 'and'), (1, 'yonder'), (1, 'with'), (1, 'window'), (1, 'what'), (1, 'through'), (1, 'sun.'), (1, 'sun'), (1, 'soft'), (1, 'sick'), (1, 'pale'), (1, 'moon.'), (1, 'light'), (1, 'kill'), (1, 'grief'), (1, 'fair'), (1, 'envious'), (1, 'east'), (1, 'breaks.'), (1, 'already'), (1, 'Who'), (1, 'Juliet'), (1, 'It'), (1, 'But'), (1, 'Arise')]
-------------
[('yonder', 1), ('with', 1), ('window', 1), ('what', 1), ('through', 1), ('the', 3), ('sun.', 1), ('sun', 1), ('soft', 1), ('sick', 1), ('pale', 1), ('moon.', 1), ('light', 1), ('kill', 1), ('is', 3), ('grief', 1), ('fair', 1), ('envious', 1), ('east', 1), ('breaks.', 1), ('and', 3), ('already', 1), ('Who', 1), ('Juliet', 1), ('It', 1), ('But', 1), ('Arise', 1)]


3. Invert the following dictionary to indicate fruit and color

In [37]:
c2f = {'green': ['watermelon', 'pear'],
 'red': ['pomegranate', 'cherry'],
 'orange': ['peach', 'orange'],
 'yellow': ['banana'],
 'purple': ['plum']}

In [43]:
f2c = {}
for color in c2f:
    for fruits in c2f[color]:
        f2c[fruits] = color
f2c

{'watermelon': 'green',
 'pear': 'green',
 'pomegranate': 'red',
 'cherry': 'red',
 'peach': 'orange',
 'orange': 'orange',
 'banana': 'yellow',
 'plum': 'purple'}

In [55]:
# invert the f2c again
c2f = {}
for f,c in f2c.items():
    if c not in c2f:
        c2f[c] = [f]
c2f

{'green': ['watermelon'],
 'red': ['pomegranate'],
 'orange': ['peach'],
 'yellow': ['banana'],
 'purple': ['plum']}

In [56]:
# invert the f2c again
c2f = {}
for f,c in f2c.items():
    if c not in c2f:
        c2f[c] = [f]
    else:
       c2f[c].append(f) 
c2f

{'green': ['watermelon', 'pear'],
 'red': ['pomegranate', 'cherry'],
 'orange': ['peach', 'orange'],
 'yellow': ['banana'],
 'purple': ['plum']}

4. Create a function to count the number of i in all the arguments. Number of arguments are unknown

In [57]:
state = "Mississippi"
   ...: state.count('i')

4

In [70]:
def count_letter_i(*args):
    i_count = {}
    for word in args:
        i_count[word] = (word.count('i'))
    return(i_count)
count_letter_i("Mississippi", "Arkansas", "Michigan")

{'Mississippi': 4, 'Arkansas': 0, 'Michigan': 2}

In [64]:
state = ["Mississippi", "Arkansas", "Michigan"]
   ...: def count_letter_i(args):
   ...:     for word in args:
   ...:         print(word.count('i'))
   ...: 
   ...: count_letter_i(state)
   ...: state

4
0
2


['Mississippi', 'Arkansas', 'Michigan']

5. Create a lambda function to extract the surname from the names: "Samridhi Dutta", "Ronit Singh", "Narender Modi"

In [78]:
# without lambda function
names = ["Samridhi Dutta", "Ronit Singh", "Narender Modi"]
def surname_split(args):
    for name in names:
        surname = name.rsplit(" ")[1]
        print(surname)
surname_split(names)

Dutta
Singh
Modi


In [81]:
f =  lambda x: x.split(" ")[1]
f("Samridhi Dutta")

'Dutta'

In [84]:
 f =  lambda x: x.split(" ")[1]
   ...: for name in names:
   ...:     print(f(name))

Dutta
Singh
Modi


In [88]:
f =  lambda x: x.split(" ")[1]
   ...: surnames = list(map(f, names))
   ...: print(surnames)

['Dutta', 'Singh', 'Modi']


In [83]:
surname = list(map(lambda x: x.split(" ")[1], names))
surname

['Dutta', 'Singh', 'Modi']

6. Convert the following temp in degree celsius to fahrenheit using lambda and map fns.

In [85]:
 temp = [36.5, 37, 37.5,39]
   ...: #fahrenheit = (9/5)*temp + 32
   ...: ftemp = []
   ...: for tt in temp:
   ...:     ftt = (9/5)*tt + 32
   ...:     ftemp.append(ftt)
   ...: print(ftemp)

[97.7, 98.60000000000001, 99.5, 102.2]


In [87]:
ftemp = []
   ...: f = lambda x: (9/5)*x + 32
   ...: for tt in temp:
   ...:     ftt = f(tt)
   ...:     ftemp.append(ftt)
   ...: print(ftemp)

[97.7, 98.60000000000001, 99.5, 102.2]


In [90]:
 f = lambda x: (9/5)*x + 32
   ...: c = lambda x: (x - 32) * 5/9
   ...: fahrenheit = list(map(f, temp))
   ...: celcius = list(map(c,fahrenheit))
   ...: 
   ...: print(fahrenheit)
   ...: print("-----------")
   ...: print(celcius)

[97.7, 98.60000000000001, 99.5, 102.2]
-----------
[36.5, 37.00000000000001, 37.5, 39.0]


7. Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization.

In [93]:
def findDog(x):
   ...:     k = x.count('dog')
   ...:     print(k>0)

In [94]:
findDog('Is there a dog here?')

True


8. Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases, where punctuation assigned to the word dog. 

In [97]:
 #### count the words in a statement
   ...: def countDog(x):
   ...:     k = x.count('dog')
   ...:     return(k)
   ...: countDog('Is there a dog here?')   

1

In [98]:
countDog('This dog runs faster than the other dog dude!')

2

9. Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'. For example:**

    seq = ['soup','dog','salad','cat','great']

**should be filtered down to:**

    ['soup','salad']

In [102]:
seq = ['soup','dog','salad','cat','great']

In [103]:
 s_logical = list(filter(lambda x: x.startswith('s') == True, seq))
   ...: print(s_logical)

['soup', 'salad']


10. You are driving a little too fast, and a police officer stops you. Write a function
  to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
  If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
  and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all cases.

In [104]:

In [1]: def caught_speeding(speed, is_birthday):
   ...:     if is_birthday:
   ...:         speed = speed - 5
   ...:     if speed <= 60:
   ...:         print("No Ticket")
   ...:     elif speed <= 80:
   ...:         print("Small Ticket")
   ...:     else:
   ...:         print("Big Ticket")

In [105]:
caught_speeding(81,True)

Small Ticket


In [106]:
caught_speeding(81,False)

Big Ticket


# Exercise -3 (List )

In [23]:
'''
Question1:

Write a program to the largest number from the list given below:

listExample1 = [8,9,13,2,3,99,6,7,4,3]

'''
listExample1 = [8,9,13,2,3,99,6,7,4,3]

def getLargest(lst):
    Largest = 0
    for number in lst:
        if number > Largest:
            Largest = number
    return(Largest)
            
getLargest(listExample1)


99

In [24]:
max_val = lambda x: sorted(x)[-1]
max_val(listExample1)

99

In [25]:
listExample1 = [8,9,13,2,3,99,6,7,4,3]
max(listExample1)

99

In [26]:
'''
Question2:

Write a program to sum all the items from the list given below:



'''
def lst_sum(lst):
    s = 0
    for k in lst:
        s = s + k
    return(s)
listExample2 = [9,8,7,6,5,4,3]
lst_sum(listExample2)

42

In [27]:
listExample2 = [9,8,7,6,5,4,3]
sum(listExample2)

42

In [28]:
'''
Question3:

Write a program to remove duplicate values from the list given below:

'''
listExample3 = [1,1,1,2,3,44,44,9,9,1,4,44]

list(set(listExample3))

[1, 2, 3, 4, 9, 44]

In [29]:
def remove_duplicate(lst):
   ...:     new_list = []
   ...:     for i in lst:
   ...:         if i not in new_list:
   ...:             new_list.append(i)
   ...:     return(new_list)

In [30]:
remove_duplicate(listExample3)

[1, 2, 3, 44, 9, 4]

In [31]:
listExample3 = [1,1,1,2,3,44,44,9,9,1,4,44]
set(listExample3)

{1, 2, 3, 4, 9, 44}

# Assignment - 4 Lists / List Comprehensions

#### Excercise 1:
Calculate the average of each sublist and append it to averages.

In [5]:
grades = [[10,20,30],[40,50,60],[70,80,90]]

In [6]:
def avg_sublist(args):
   ...:     sub_list_average = []
   ...:     for sub_lst in grades:
   ...:         sub_sum = 0
   ...:         lng = len(sub_lst)
   ...:         for k in sub_lst:
   ...:             sub_sum = sub_sum + k
   ...:             avg = sub_sum/lng
   ...:         sub_list_average.append(avg)
   ...:     return(sub_list_average)

In [7]:
avg_sublist(grades)

[20.0, 50.0, 80.0]

In [14]:
  # using lambda function     
   ...: averages = list(map(lambda x : sum(x)/len(x), grades))
   ...: print(averages)

[20.0, 50.0, 80.0]


150.0

#### Excercise 2:
Create a list with the elements as the square of each element in the input list

In [20]:
 def square_fun(lst):
   ...:     temp = list(map(lambda x: x**2, lst))
   ...:     return(temp)

In [21]:
lst = [1,5,7,3,9]
square_fun(lst)

[1, 25, 49, 9, 81]

In [22]:
temp = list(map(lambda x: x**2, lst))
temp

[1, 25, 49, 9, 81]

#### Exercise 3:
Calculate the averages of numbers in a list of list
l = [[1,2,3], [4,5,6]]

In [26]:
l = [[1,2,3], [4,5,6]]
# using lambda function     
averages = list(map(lambda x : sum(x)/len(x), l))
print(averages)

[2.0, 5.0]


#### Exercise 4:
Print the unique elements in this list
duplicates = [1, 2, 3, 1, 2, 5, 6, 7, 8]
Print the unique elements in the above list without the small numbers [1,2,3] ## Hint use the difference method from sets

In [28]:
dublicates = [1, 2, 3, 1, 2, 5, 6, 7, 8]
print(list(set(dublicates)))

[1, 2, 3, 5, 6, 7, 8]


In [29]:
 # without [1,2,3]
   ...: A = set(duplicates)
   ...: B = set([1,2,3])
   ...: A.difference(B)

{5, 6, 7, 8}

In [30]:
 # without [1,2,3]        
   ...: A = set(duplicates)      
   ...: B = set([1,2,3])
   ...: C = list(A.difference(B))
   ...: print(C)

[8, 5, 6, 7]


#### Exercise 5.
Transpose of Matrix using Nested Loops
a = [[1,2,3], [4,5,6]]

In [32]:
a = [[1,2,3], [4,5,6]]
   ...: at = []
   ...: for row in a:
   ...:     for i in row:     
   ...:         at.append(i)  
   ...: at

[1, 2, 3, 4, 5, 6]

In [39]:
 a = [[1,2,3], [4,5,6]]
   ...: at = []
   ...: for i in range(3):
   ...:     bt = []
   ...:     for row in a:
   ...:         bt.append(row[i])
   ...:     at.append(bt)
   ...: at

[[1, 4], [2, 5], [3, 6]]

#### Exercise 6: 
Join the elements in the list to represent in date format: dd-mm-YYYY and split it back to represent in the same format for following list:
[19, 7, 2019]

In [40]:
 dd = [19, 7, 2019]
   ...: dt = ''.join(str(e) for e in dd)
   ...: dt
   

'1972019'

In [43]:
import datetime
   ...: date_str = ''.join(str(e) for e in dd)
   ...: format_str = '%d%m%Y' # The format
   ...: datetime_obj = datetime.datetime.strptime(date_str, format_str)

In [45]:
 print(datetime_obj.date())

2019-07-19


In [47]:
  # current dateTime
   ...: from datetime import datetime
   ...: now = datetime.now()
   ...: 
   ...: # convert to date String
   ...: date = now.strftime("%d/%m/%Y")
   ...: print('Date String:', date)

Date String: 28/07/2022


In [50]:
 # convert to dd - mm - yyyy format
   ...: date = datetime_obj.strftime('%d-%m-%Y')
   ...: print('Converted dd-mm-yyyy format date:', date)

Converted dd-mm-yyyy format date: 19-07-2019


#### Exercise 7:
Find a way to convert this list into unidimensional
[[1,2,3], [4,5,6],[7,8,9]]

In [53]:
lst = [[1,2,3], [4,5,6],[7,8,9]]
   ...: oneDim_array = []
   ...: for row in lst:
   ...:     for i in row:
   ...:         oneDim_array.append(i)  
   ...: 
   ...: print(oneDim_array)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [54]:
sum(lst, [])

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# Exercise -5 NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
array1 = np.arange(0, 9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand(1)

array([0.95149944])

array([ 0.42829726])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [14]:
np.random.normal(0, 1, 25)

array([ 0.13308492,  0.16076672,  0.05635544, -0.74371912, -0.42798209,
        1.57158072, -2.90793733,  0.41546366,  0.09923846,  0.67377931,
        1.02658362,  0.97702416,  0.72308974, -0.55855544,  0.35287434,
       -0.16532708, -0.55296751, -0.08157599, -0.35597281,  1.11341321,
       -0.97422295, -0.23658628,  0.15811922, -0.87116326, -0.64720239])

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Create the following matrix:

In [32]:
np.arange(start = 0.01, stop = 1.01, step = 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [33]:
np.linspace(0.01, 1, 100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [31]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [28]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [35]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [38]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3,4]

20

20

In [46]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
sub_mat = mat[0:3, 1]
temp = np.array(list(map(lambda x : [x], sub_mat) ))
temp

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [54]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[4:, ].reshape(5)

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [56]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3:5, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [57]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [58]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [60]:
colSum = np.sum(mat,axis = 0)
   ...: print(colSum)

[55 60 65 70 75]


In [64]:
 colSum = mat.sum(axis = 0)
   ...: print(colSum)

[55 60 65 70 75]


In [65]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])


# Exercise -6 Ecommerce Purchases Exercise

In this Exercise you will be given some Fake Data about some purchases done through Amazon! Just go ahead and follow the directions and try your best to answer the questions and complete the tasks. Feel free to reference the solutions. Most of the tasks can be solved in different ways. For the most part, the questions get progressively harder.

Please excuse anything that doesn't make "Real-World" sense in the dataframe, all the data is fake and made-up.

Also note that all of these questions can be answered with one line of code.
____
** Import pandas and read in the Ecommerce Purchases csv file and set it to a DataFrame called ecom. **

In [1]:
import numpy as np
import pandas as pd

In [5]:
file_path = "C:/Users/Apsu/Desktop/Simplilearn_course1_folder/Day-1-materials/Datasets/Ecommerce_Purchases.txt"
ecom = pd.read_csv(file_path, sep =',')

In [6]:
ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Address           10000 non-null  object 
 1   Lot               10000 non-null  object 
 2   AM or PM          10000 non-null  object 
 3   Browser Info      10000 non-null  object 
 4   Company           10000 non-null  object 
 5   Credit Card       10000 non-null  int64  
 6   CC Exp Date       10000 non-null  object 
 7   CC Security Code  10000 non-null  int64  
 8   CC Provider       10000 non-null  object 
 9   Email             10000 non-null  object 
 10  Job               10000 non-null  object 
 11  IP Address        10000 non-null  object 
 12  Language          10000 non-null  object 
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [10]:
ecom[0:4]

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   

   CC Security Code   CC Provider                           Email  \
0               900  JCB 16 digit               pdunlap@yahoo.com   
1               561    Mastercard              anthony41@reed.com   
2               699  JCB 16 digit  amymiller@morales-harrison.com   
3               384      Discover     brent16@olson-robinson.info   

                                      Job       IP Address Language  \
0  Scientist, product/process development  149.146.147.205       el   
1                       Drilling engineer     15.160.41.51       fr   
2                Customer service manager   132.207.160.22       de   
3                       Drilling engineer     30.250.74.19       es   

   Purchase Price  
0           98.14  
1           70.73  
2            0.95  
3           78.04

**Check the head of the DataFrame.**

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

** How many rows and columns are there? **

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
Address             10000 non-null object
Lot                 10000 non-null object
AM or PM            10000 non-null object
Browser Info        10000 non-null object
Company             10000 non-null object
Credit Card         10000 non-null int64
CC Exp Date         10000 non-null object
CC Security Code    10000 non-null int64
CC Provider         10000 non-null object
Email               10000 non-null object
Job                 10000 non-null object
IP Address          10000 non-null object
Language            10000 non-null object
Purchase Price      10000 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


** What is the average Purchase Price? **

In [16]:
pruchase_price = ecom["Purchase Price"]
print("Average purchase price", np.mean(pruchase_price))

Average purchase price 50.34730200000025


** What were the highest and lowest purchase prices? **

In [18]:
print("highest purchase price is {} and lowest purchase price is {}".format(pruchase_price.max(),pruchase_price.min()) )

highest purchase price is 99.99 and lowest purchase price is 0.0


99.989999999999995

0.0

** How many people have English 'en' as their Language of choice on the website? **

In [19]:
ecom["Language"].value_counts()["en"]

1098

Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
dtype: int64

** How many people have the job title of "Lawyer" ? **


In [20]:
ecom["Job"].value_counts()["Lawyer"]

30

In [23]:
import re
   ...: 
   ...: sum(~ecom["Job"].apply(lambda x: re.search("[lL]awyer", x)).isnull())

30

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 470 to 9979
Data columns (total 14 columns):
Address             30 non-null object
Lot                 30 non-null object
AM or PM            30 non-null object
Browser Info        30 non-null object
Company             30 non-null object
Credit Card         30 non-null int64
CC Exp Date         30 non-null object
CC Security Code    30 non-null int64
CC Provider         30 non-null object
Email               30 non-null object
Job                 30 non-null object
IP Address          30 non-null object
Language            30 non-null object
Purchase Price      30 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 3.5+ KB


** How many people made the purchase during the AM and how many people made the purchase during PM ? **

**(Hint: Check out [value_counts()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html) ) **

In [21]:
ecom["AM or PM"].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

PM    5068
AM    4932
Name: AM or PM, dtype: int64

** What are the 5 most common Job Titles? **

In [25]:
ecom["Job"].value_counts()[0:5]

Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: Job, dtype: int64

Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: Job, dtype: int64

** Someone made a purchase that came from Lot: "90 WT" , what was the Purchase Price for this transaction? **

In [27]:
ecom[ecom["Lot"] == "90 WT"]["Purchase Price"]

513    75.1
Name: Purchase Price, dtype: float64

In [28]:
ecom.loc[ecom["Lot"] == "90 WT", "Purchase Price"]

513    75.1
Name: Purchase Price, dtype: float64

513    75.1
Name: Purchase Price, dtype: float64

** What is the email of the person with the following Credit Card Number: 4926535242672853 **

In [29]:
ecom.loc[ecom["Credit Card"] == 4926535242672853, "Email"]

1234    bondellen@williams-garza.com
Name: Email, dtype: object

1234    bondellen@williams-garza.com
Name: Email, dtype: object

** How many people have American Express as their Credit Card Provider *and* made a purchase above $95 ?**

In [31]:
temp = ecom.loc[ecom["CC Provider"] == "American Express", "Purchase Price"]
len(temp[temp > 95])

39

In [32]:
sum((~ecom["CC Provider"].apply(lambda x: re.search("American Express", x)).isnull())
   ...:     & (ecom["Purchase Price"]>95))

39

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

** Hard: How many people have a credit card that expires in 2025? **

In [33]:
sum((~ecom["CC Exp Date"].apply(lambda x: re.search("/25", x)).isnull()))

1033

** Hard: What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc...) **

In [34]:
ecom["Email"].str.split("@")

0                    [pdunlap, yahoo.com]
1                   [anthony41, reed.com]
2       [amymiller, morales-harrison.com]
3          [brent16, olson-robinson.info]
4          [christopherwright, gmail.com]
                      ...                
9995            [iscott, wade-garner.com]
9996                [mary85, hotmail.com]
9997                 [tyler16, gmail.com]
9998           [elizabethmoore, reid.net]
9999             [rachelford, vaughn.com]
Name: Email, Length: 10000, dtype: object

In [41]:
ecom["Email"].str.split("@").str[1].value_counts()[:5]

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: Email, dtype: int64